# =============================================================
# Common role — выполняется для всех продуктов
# =============================================================

---
- include_tasks: "{{ role_path }}/tasks/licenses.yml"
